
- name: Check if Disk is Encrypted
  ansible.builtin.shell: cryptsetup isLuks $(blkid | grep crypto | sed -E 's/:.+//g')
  register: command_result
  failed_when: command_result.stdout | length > 0
  changed_when: command_result.stdout | length > 0